# Generated by Django 5.2.16 on 2026-07-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0010_alter_dish_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, verbose_name="手机号"),
        ),
        migrations.CreateModel(
            name="FamilyNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_plan_date", models.DateField(verbose_name="排餐日期")),
                (
                    "meal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "早餐"),
                            ("lunch", "午餐"),
                            ("dinner", "晚餐"),
                            ("snack", "许愿·小零嘴"),
                        ],
                        max_length=20,
                        verbose_name="餐次",
                    ),
                ),
                (
                    "change_summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="变更摘要"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提醒时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_family_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="meals.family",
                        verbose_name="家庭",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_family_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被提醒人",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["family", "-created_at"],
                        name="meals_famil_family__3fc848_idx",
                    ),
                    models.Index(
                        fields=["family", "recipient", "-created_at"],
                        name="meals_famil_family__4bf5c2_idx",
                    ),
                ],
            },
        ),
    ]
