# Generated by Django 5.2.16 on 2026-07-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0013_notification_email_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="familynotification",
            name="recipient_deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="收件人隐藏时间"
            ),
        ),
    ]
